services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: inventario-php
        volumes:
            - .:/var/www/html/vanilla-inventario
        ports:
            - 8080:80
        networks:
            - inventario-network

    mysql:
        image: mysql:8.0.23
        container_name: inventario-mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: inventario
            MYSQL_USER: inventario-user
            MYSQL_PASSWORD: inventario-pass
        volumes:
            - inventario-mysql-volume:/etc/mysql/conf.d
        networks:
            - inventario-network
networks:
    inventario-network:

volumes:
    inventario-mysql-volume: